## example train file
data: "/home/z/data/Face/FFHQ_128"

train:
  ema_decay: 0.995
  train_batch_size: 64
  train_lr: 2e-5
  train_num_steps: 100000
  gradient_accumulate_every: 2
  fp16: True
  step_start_ema: 2000
  update_ema_every: 10
  save_and_sample_every: 1000
  results_folder: './results_ffhq'  # training floder
  resize_images: False
  milestone: 'last' # load last milestone | or number '15000'
  num_workers: 4

diffusion:
  image_size: 128
  timesteps: 1000
  loss_type: 'l1'
  betas:

model:
  dim: 64
  out_dim:
  dim_mults: [1, 2, 4, 8]
  channels: 3
  with_time_emb: True
